window.GEO_COURSE = (() => {
  const lessonMeta = {
    "conceptos": { minutes: 35, priority: "CRÍTICA", description: "Cartografía, espacio geográfico, límites, cuencas y vocabulario base.", keys: ["Paralelos: este-oeste; meridianos: norte-sur.", "Escala: relación proporcional entre mapa y realidad.", "Cuenca exorreica desemboca en mares u océanos; endorreica pierde agua por evaporación; arreica es intermitente.", "Territorio implica ejercicio de poder; región agrupa rasgos semejantes y tiene bordes difusos.", "Condición de sitio describe el lugar; condición de posición explica su relación con otros espacios."] },
    "argentina": { minutes: 30, priority: "ALTA", description: "Patrones de relieve, clima, vientos, población e infraestructura nacional.", keys: ["Oeste predominantemente montañoso; este predominantemente llano.", "Norte cálido, centro templado, oeste árido, este húmedo y sur frío.", "Zonda: cálido y seco; sudestada: fría y húmeda; pampero: frío y seco.", "La red de transporte es radial y se concentra históricamente en Buenos Aires.", "Argentina es mayoritariamente urbana y su población se distribuye de manera desigual."] },
    "nea": { minutes: 45, priority: "ALTA", description: "Llanuras, mesetas, grandes ríos y circuitos del litoral.", keys: ["Incluye Misiones, Corrientes, Entre Ríos, Formosa, Chaco y Santa Fe.", "Misiones tiene mesetas de origen volcánico, suelo laterítico y selva subtropical.", "Los Esteros del Iberá se ubican en Corrientes y tienen abundante aporte hídrico.", "Ruta 11 conecta Santa Fe, Chaco y Formosa; la 12 recorre Paraná; la 14 acompaña al Uruguay.", "Iguazú protege la selva misionera y articula circuitos superior, inferior, Macuco y Garganta del Diablo."] },
    "noa": { minutes: 45, priority: "ALTA", description: "Puna, cordillera oriental, quebradas, valles y sierras subandinas.", keys: ["NOA: Jujuy, Salta, Tucumán, Catamarca, Santiago del Estero y La Rioja.", "La Puna es un altiplano árido y frío, de gran amplitud térmica.", "Los valles son amplios y concentran población; las quebradas son angostas y profundas.", "Las sierras subandinas tienen clima subtropical con estación seca y vegetación densa.", "La altura, la escasez de agua y la amplitud térmica condicionan turismo y poblamiento."] },
    "cuyo": { minutes: 40, priority: "ALTA", description: "Oasis, cordillera, piedemonte, Zonda y rutas vitivinícolas.", keys: ["Cuyo está integrado por Mendoza, San Juan y San Luis.", "Los oasis administran agua de deshielo mediante canales y acequias.", "El Zonda es cálido, seco y violento; los terremotos se vinculan al choque de placas.", "La Ruta 40 une San Juan y Mendoza; la Ruta 7 conecta Buenos Aires, Mendoza y Chile.", "San Luis no tiene cordillera y combina llanura, sierras pampeanas y pampa seca."] },
    "patagonia": { minutes: 45, priority: "CRÍTICA", description: "Dos corredores que ordenan paisajes y destinos muy diferentes.", keys: ["La Patagonia andina se estructura sobre la Ruta 40.", "La Patagonia extrandina y costera se organiza sobre la Ruta 3.", "Bariloche, San Martín de los Andes y El Calafate son nodos del corredor andino.", "Puerto Madryn, Península Valdés y Punta Tombo integran el corredor atlántico.", "Los Andes descargan humedad al oeste y explican la aridez de las mesetas orientales."] },
    "buenos-aires": { minutes: 40, priority: "MEDIA", description: "Corredores, costa atlántica, miniturismo y turismo urbano-rural.", keys: ["La provincia ofrece turismo rural, urbano, cultural, histórico, de eventos y de sol y playa.", "San Isidro y Tigre forman parte del corredor norte y tienen acceso ferroviario.", "El Delta del Paraná crece por depósito de sedimentos.", "El Puerto de Frutos pasó de mercado productivo a centro de compras turístico.", "La costa atlántica concentra balnearios y marcada estacionalidad veraniega."] },
    "america-norte": { minutes: 50, priority: "ALTA", description: "Canadá, Estados Unidos y México: grandes conjuntos y destinos.", keys: ["Canadá organiza su relieve en Rocallosas, grandes llanuras y Escudo Canadiense.", "El sur canadiense concentra población y clima más templado.", "México tiene Sierras Madre, mesetas interiores, volcanes y llanuras costeras angostas.", "Los huracanes condicionan la temporada turística mexicana entre junio y octubre.", "México combina turismo colonial, arqueológico, urbano, de naturaleza y sol y playa."] },
    "caribe": { minutes: 40, priority: "ALTA", description: "Islas, volcanismo, resorts y efectos territoriales del turismo.", keys: ["América Central se extiende entre México y Colombia; el Caribe incluye el espacio insular y costas caribeñas.", "Las islas volcánicas son montañosas; las coralinas son bajas, llanas y de arena clara.", "Costa Rica se destaca por parques nacionales y turismo sustentable.", "Panamá combina canal, compras y turismo empresarial.", "El modelo all inclusive puede producir privatización, elitización, empleo precario y dependencia del turismo."] },
    "america-sur": { minutes: 50, priority: "ALTA", description: "Países andinos, amazónicos y caribeños con sus grandes circuitos.", keys: ["Colombia concentra población en regiones andina y caribeña; la Amazonia está menos poblada.", "Bogotá integra turismo urbano y de negocios; Cartagena combina patrimonio colonial y playa.", "Ecuador se divide en costa, Andes, Amazonia y Galápagos.", "Lima está en la costa árida influida por la corriente fría de Humboldt.", "Cusco es base del turismo incaico y de acceso a Machu Picchu."] },
    "cordoba": { minutes: 30, priority: "MEDIA", description: "Regiones serranas, festivales, patrimonio jesuítico y naturaleza.", keys: ["Calamuchita incluye Villa General Belgrano, Embalse y La Cumbrecita.", "Punilla concentra La Falda, Cosquín, Villa Carlos Paz y el Cerro Uritorco.", "Alta Gracia combina museos y patrimonio jesuítico.", "Sierras Chicas incluye Colonia Caroya y Jesús María.", "Traslasierra reúne Villa Cura Brochero, Mina Clavero y balnearios naturales."] }
  };

  const flashcards = [
    ["Escala", "Relación proporcional entre lo representado en el mapa y la superficie real."], ["Territorio", "Espacio geográfico organizado por relaciones de poder."],
    ["Región", "Construcción que agrupa rasgos semejantes; tiene centralidades claras y bordes difusos."], ["Exorreica", "Cuenca que lleva sus aguas a mares u océanos."],
    ["Endorreica", "Cuenca sin salida al mar, donde el agua se pierde principalmente por evaporación."], ["Puna", "Altiplano elevado, árido y frío del NOA."],
    ["Zonda", "Viento cálido, seco y fuerte característico de Cuyo."], ["Oasis cuyano", "Área irrigada con agua de deshielo mediante canales y acequias."],
    ["Ruta 40", "Eje del oeste argentino y del corredor patagónico andino."], ["Ruta 3", "Eje del corredor patagónico atlántico o extrandino."],
    ["Suelo laterítico", "Suelo rojizo de Misiones por oxidación del hierro."], ["Iberá", "Sistema de esteros y humedales del centro-norte de Corrientes."],
    ["Delta", "Área de depósito de sedimentos donde un río forma islas y nuevos terrenos."], ["Isla coralina", "Isla baja formada por acumulación de coral y arena."],
    ["All inclusive", "Modelo de resort que concentra servicios y gasto turístico dentro del complejo."], ["Monoproducto turístico", "Dependencia de una única actividad económica: el turismo."],
    ["Humboldt", "Corriente marina fría que influye en la costa peruana y favorece riqueza pesquera."], ["Galápagos", "Archipiélago ecuatoriano de biodiversidad singular y turismo controlado."],
    ["Miniturismo", "Viaje breve y cercano, frecuente en la provincia de Buenos Aires."], ["Punilla", "Región cordobesa muy turística con Cosquín, Carlos Paz y La Falda."]
  ];

  const q = (topic, prompt, options, answer, explanation) => ({ topic, prompt, options, answer, explanation });
  const questions = [
    q("conceptos", "¿Qué línea imaginaria divide la Tierra en hemisferios norte y sur?", ["Greenwich", "Ecuador", "Antimeridiano", "Trópico de Capricornio"], 1, "El Ecuador es el paralelo 0 y divide norte y sur."),
    q("conceptos", "¿Cómo se orientan los meridianos?", ["De este a oeste", "De norte a sur", "Sólo sobre el Ecuador", "En círculos paralelos"], 1, "Los meridianos recorren la Tierra de norte a sur."),
    q("conceptos", "Una cuenca que desemboca en el océano es...", ["Arreica", "Endorreica", "Exorreica", "Geodésica"], 2, "Las cuencas exorreicas tienen salida hacia mares u océanos."),
    q("conceptos", "¿Qué concepto pone el acento en el ejercicio de poder sobre un espacio?", ["Paisaje", "Territorio", "Punto", "Ruta"], 1, "El territorio es un espacio atravesado por relaciones de poder."),
    q("conceptos", "¿Cuál es la relación correcta entre mapa y detalle?", ["Mapa: poca extensión y mucho detalle", "Plano: gran extensión y poco detalle", "Mapa: gran extensión y poco detalle", "Carta: siempre sin escala"], 2, "Los mapas cubren gran extensión con menor detalle; los planos hacen lo contrario."),
    q("conceptos", "Las condiciones de sitio describen...", ["La relación política entre dos países", "Las características naturales y sociales del lugar", "Sólo la distancia en kilómetros", "Únicamente la actividad turística"], 1, "Sitio responde cómo es el lugar; posición, cómo se relaciona con otros."),
    q("argentina", "¿Qué patrón general presenta el relieve argentino?", ["Montañas al este y llanuras al oeste", "Llanuras al este y montañas al oeste", "Mesetas sólo al norte", "Relieve uniforme"], 1, "En el oeste predominan montañas y en el este, llanuras."),
    q("argentina", "¿Cuál viento es cálido y seco?", ["Sudestada", "Pampero", "Zonda", "Polar"], 2, "El Zonda es cálido y seco, típico de Cuyo."),
    q("argentina", "La red de transporte radial argentina se concentra históricamente en...", ["Córdoba", "Mendoza", "Buenos Aires", "Ushuaia"], 2, "La estructura agroexportadora concentró conexiones en Buenos Aires."),
    q("argentina", "¿Dónde predominan los climas áridos?", ["Este", "Oeste", "Noreste húmedo", "Centro-este"], 1, "La aridez aumenta hacia el oeste."),
    q("nea", "¿Cuál grupo reúne las provincias mesopotámicas?", ["Chaco, Formosa y Santa Fe", "Misiones, Corrientes y Entre Ríos", "Salta, Jujuy y Tucumán", "Mendoza, San Juan y San Luis"], 1, "Misiones, Corrientes y Entre Ríos están entre grandes ríos."),
    q("nea", "¿Por qué el suelo misionero es rojizo?", ["Por sal marina", "Por óxido de hierro", "Por arena volcánica blanca", "Por acumulación de coral"], 1, "El hierro de materiales volcánicos se oxida y da el color laterítico."),
    q("nea", "¿Dónde se ubican los Esteros del Iberá?", ["Chaco", "Corrientes", "Entre Ríos", "Misiones"], 1, "El Iberá ocupa el centro-norte correntino."),
    q("nea", "¿Qué ruta bordea principalmente el río Uruguay?", ["11", "12", "14", "40"], 2, "La Ruta 14 recorre el corredor del Uruguay."),
    q("nea", "¿Qué circuito de Iguazú llega al salto de mayor caudal?", ["Tren ecológico hacia Garganta del Diablo", "Circuito de la Ruta 14", "Paseo del Iberá", "Sendero del Delta"], 0, "El tren ecológico conecta el ingreso con la estación Garganta del Diablo."),
    q("noa", "¿Qué relieve caracteriza a la Puna?", ["Llanura costera húmeda", "Altiplano elevado", "Delta sedimentario", "Meseta coralina"], 1, "La Puna es una llanura elevada o altiplano."),
    q("noa", "¿Cuál es el clima típico de la Puna?", ["Cálido y húmedo", "Templado oceánico", "Árido y frío", "Subtropical sin estación seca"], 2, "La altura y aridez producen frío y gran amplitud térmica."),
    q("noa", "¿Qué diferencia principal hay entre valle y quebrada?", ["El valle es más amplio y poblado", "La quebrada siempre tiene clima tropical", "El valle carece de actividades", "No existe diferencia"], 0, "Los valles son amplios; las quebradas, estrechas y profundas."),
    q("noa", "¿Dónde aparecen las sierras subandinas?", ["Salta, Jujuy y Tucumán", "Mendoza y San Juan", "Chubut y Santa Cruz", "Buenos Aires y La Pampa"], 0, "El documento las localiza en Salta, Jujuy y Tucumán."),
    q("cuyo", "¿Qué provincias integran Cuyo?", ["Mendoza, San Juan y San Luis", "La Rioja, Catamarca y Córdoba", "Neuquén, Río Negro y Chubut", "Salta, Jujuy y Tucumán"], 0, "La región está compuesta por Mendoza, San Juan y San Luis."),
    q("cuyo", "¿Cuál es la fuente principal del agua de los oasis?", ["Mareas", "Deshielo", "Humedad atlántica", "Aguas coralinas"], 1, "Los ríos cuyanos se alimentan principalmente del deshielo."),
    q("cuyo", "¿Qué ruta conecta Buenos Aires, Mendoza y Santiago de Chile?", ["Ruta 3", "Ruta 7", "Ruta 12", "Ruta 14"], 1, "La Ruta 7 es un eje nacional e internacional."),
    q("cuyo", "¿Qué distingue a San Luis dentro de Cuyo?", ["Tiene las mayores alturas andinas", "No cuenta con cordillera", "Carece de llanuras", "Es la única con oasis"], 1, "San Luis combina llanura, sierras pampeanas y pampa seca, sin cordillera."),
    q("patagonia", "¿Qué ruta estructura la Patagonia andina?", ["Ruta 3", "Ruta 9", "Ruta 40", "Ruta 14"], 2, "La Ruta 40 conecta los destinos cordilleranos."),
    q("patagonia", "¿Qué ruta organiza la Patagonia extrandina?", ["Ruta 3", "Ruta 7", "Ruta 11", "Ruta 40"], 0, "La Ruta 3 recorre el corredor atlántico."),
    q("patagonia", "¿Cuál destino pertenece al corredor andino?", ["Puerto Madryn", "Punta Tombo", "El Calafate", "Rawson"], 2, "El Calafate integra la Patagonia andina; los otros son del corredor oriental."),
    q("patagonia", "Península Valdés se asocia principalmente con...", ["Turismo vitivinícola", "Fauna marina", "Ruinas mayas", "Turismo jesuítico"], 1, "Es un destino emblemático de observación de fauna marina."),
    q("buenos-aires", "¿Cómo se formaron las islas del Delta del Paraná?", ["Por actividad volcánica", "Por acumulación de sedimentos", "Por choque de placas", "Por corales"], 1, "Los ríos depositan sedimentos y forman nuevas tierras."),
    q("buenos-aires", "¿Qué transformación tuvo el Puerto de Frutos?", ["Pasó a ser un aeropuerto", "Se convirtió principalmente en centro de compras", "Fue cerrado al turismo", "Se transformó en puerto petrolero"], 1, "La función productiva tradicional cedió lugar al consumo turístico."),
    q("buenos-aires", "San Isidro y Tigre forman parte del...", ["Corredor norte", "Corredor andino", "Eje cafetero", "Circuito de la Puna"], 0, "Ambos integran el corredor norte bonaerense."),
    q("america-norte", "¿Cuál es el principal socio comercial de Canadá según el resumen?", ["México", "Estados Unidos", "Francia", "Brasil"], 1, "La economía canadiense está fuertemente vinculada con Estados Unidos."),
    q("america-norte", "¿Dónde se concentra el clima más templado de Canadá?", ["Norte ártico", "Sur, cerca de Estados Unidos", "Cumbres rocosas", "Islas del norte"], 1, "El sur es más templado y concentra más población."),
    q("america-norte", "¿Qué problema condiciona el turismo mexicano entre junio y octubre?", ["Sudestadas", "Huracanes", "Nevadas polares", "Zonda"], 1, "Es la temporada de tormentas tropicales y huracanes."),
    q("america-norte", "¿Qué destino mexicano se vincula con las pirámides del Sol y la Luna?", ["Teotihuacán", "Taxco", "Acapulco", "Cabo San Lucas"], 0, "Teotihuacán alberga esas pirámides."),
    q("america-norte", "La Riviera Maya se especializa especialmente en...", ["Turismo polar", "Sol y playa más arqueología", "Turismo de estancias", "Esquí de montaña"], 1, "Combina balnearios caribeños con sitios mayas."),
    q("caribe", "¿Cómo se caracteriza una isla coralina?", ["Montañosa y volcánica", "Baja, llana y formada por coral y arena", "Glaciaria y fría", "Árida por sombra de lluvia"], 1, "Las islas coralinas apenas sobresalen del mar y tienen relieve llano."),
    q("caribe", "¿Qué país se destaca por turismo sustentable y parques nacionales?", ["Costa Rica", "Cuba", "Jamaica", "Panamá"], 0, "Costa Rica basa buena parte de su oferta en áreas protegidas."),
    q("caribe", "¿Cuál atractivo estructura buena parte del turismo panameño?", ["Canal de Panamá", "Machu Picchu", "Cataratas del Iguazú", "Ruta 40"], 0, "El canal funciona también como atractivo y museo visitable."),
    q("caribe", "¿Qué riesgo implica el turismo como monoproducto?", ["Diversifica la economía", "Genera dependencia de una sola actividad", "Elimina la estacionalidad", "Garantiza empleo estable"], 1, "Una crisis turística afecta a toda la economía local."),
    q("caribe", "El modelo all inclusive suele concentrar...", ["El gasto dentro del resort", "La actividad en centros históricos", "El turismo rural", "La producción agrícola"], 0, "Alojamiento, comida y actividades se consumen dentro del complejo."),
    q("america-sur", "¿Dónde se concentra principalmente la población colombiana?", ["Amazonia", "Regiones andina y caribeña", "Sólo en islas", "Desierto de La Guajira"], 1, "Las zonas andina y caribeña son las más pobladas."),
    q("america-sur", "¿Qué ciudad colombiana combina patrimonio colonial, playas y un vínculo con García Márquez?", ["Bogotá", "Cartagena de Indias", "Cali", "Medellín"], 1, "Cartagena reúne esos tres componentes."),
    q("america-sur", "¿Cuáles son los cuatro grandes paisajes de Ecuador?", ["Costa, Andes, Amazonia e islas", "Puna, pampa, delta y meseta", "Caribe, Patagonia, Cuyo y NOA", "Desierto, tundra, taiga y sabana"], 0, "Ecuador se organiza en costa, sierra andina, Amazonia y Galápagos."),
    q("america-sur", "¿Qué corriente fría influye en la costa de Perú?", ["Brasil", "Humboldt", "Golfo", "Malvinas exclusivamente"], 1, "La corriente de Humboldt enfría la costa y favorece biodiversidad pesquera."),
    q("america-sur", "¿Qué ciudad es la base principal para visitar Machu Picchu?", ["Lima", "Cusco", "Guayaquil", "Cartagena"], 1, "Cusco fue capital incaica y es el gran nodo del circuito."),
    q("cordoba", "¿En qué región cordobesa está Villa General Belgrano?", ["Punilla", "Calamuchita", "Traslasierra", "Sierras Chicas"], 1, "Villa General Belgrano integra Calamuchita."),
    q("cordoba", "¿Qué localidad es conocida por el Festival Nacional de Folklore?", ["Cosquín", "Embalse", "Alta Gracia", "Mina Clavero"], 0, "El festival de Cosquín atrae visitantes en verano."),
    q("cordoba", "¿Dónde se encuentra el Museo Casa del Che?", ["Alta Gracia", "Villa Carlos Paz", "La Falda", "Jesús María"], 0, "La antigua vivienda de Guevara está en Alta Gracia."),
    q("cordoba", "¿Qué región incluye Villa Cura Brochero y Mina Clavero?", ["Calamuchita", "Traslasierra", "Punilla", "Paravachasca"], 1, "Ambas localidades integran Traslasierra.")
  ];

  const sections = window.GEO_MATERIAL || [];
  const lessons = sections.map(section => ({ ...section, ...lessonMeta[section.id] }));
  return { lessons, flashcards, questions };
})();
